keys:
  - &user_brian age1g5st2tr6aze2m3dc0pm9m0rk0hf8qjkwggmcz3kwcu4kvw60tfgsj5u9q6
  - &host_nixos age143q88vkea3kgak0whxwjntzumdlefr954yfz6ruweygatl6pv56sgpx2aj
  - &host_pc age102048qx8takfawlx09qxak4kvrscajndpnulul08peq556p48elskqhqhd

creation_rules:
  - path_regex: secrets/.*$
    key_groups:
      - age:
          - *user_brian
          - *host_nixos
          - *host_pc